version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
    restart: always
  server:
    container_name: server
    build: .
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LABEL_STUDIO_USE_REDIS=true
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
      # - label-studio
    volumes:
      - "./data/server:/data"
      - "./logs:/tmp"
    restart: always
  # label-studio:
  #   container_name: label-studio
  #   image: heartexlabs/label-studio:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./mydata:/label-studio/data"
  #   restart: always